export const exampleValues = {
  "agent-manifest": {
    agentName: "Workshop Planning Assistant",
    purpose: "Help a facilitator turn a public workshop idea into clear planning artifacts.",
    scope: "Supports agenda drafting, checklist creation, and follow-up note organization for synthetic workshop scenarios.",
    owners: "Example program facilitator\nLearning experience maintainer",
    relatedSystems: "Public template library\nLocal Markdown workspace\nSynthetic checklist collection",
  },
  "role-profile": {
    role: "Planning collaborator",
    audience: "Builders learning agent artifact design",
    tone: "Clear, practical, and beginner-friendly",
    autonomy: "Medium - drafts for review",
    boundaries: "Drafts artifacts for human review\nDoes not make commitments on behalf of a person\nEscalates unclear safety or privacy questions\nUses only synthetic examples",
  },
  "operating-principles": {
    principles: "Make assumptions visible\nPrefer small reversible steps\nKeep examples public-safe",
    decisionRules: "Ask for review before changing artifact scope\nUse the catalog bucket as the organizing anchor",
    escalationRules: "Escalate when a request includes private data\nPause when taxonomy placement is unclear",
    communicationStyle: "Use concise explanations and show how each artifact connects to nearby artifacts.",
  },
  "skill-module": {
    skillName: "Synthetic Workshop Outline Skill",
    trigger: "Use when a learner needs a reusable workflow for outlining a generic workshop.",
    inputs: "Topic\nAudience level\nTimebox\nDesired artifact outputs",
    workflow: "Clarify the learning goal\nDraft a timed outline\nList required public-safe materials\nIdentify follow-up artifacts",
    outputs: "Workshop outline draft\nMaterials checklist\nRelated artifact list\nOpen questions for review",
  },
  "tool-spec": {
    toolName: "Template Lookup",
    purpose: "Find a matching public-safe starter template from a local collection.",
    parameters: "topic: Public-safe subject string\nartifactType: Catalog artifact id\nformat: markdown | yaml",
    permissions: "Read local public template files\nReturn template metadata only\nAvoid network access in the starter spec",
    failureModes: "No matching template found\nTemplate metadata is incomplete\nRequested artifact type is unknown",
  },
  "resource-manifest": {
    resourceName: "Public Learning Notes",
    resourceType: "Static reference collection",
    allowedUse: "Use as background material for synthetic examples and beginner explanations.",
    freshness: "Review once per release cycle.",
    accessNotes: "Stored as public Markdown files with no private links, credentials, account ids, or private endpoints.",
  },
  "system-task-prompt": {
    promptPurpose: "Guide the model to generate beginner-readable artifact drafts.",
    instructions: "Use the selected catalog artifact as the source of structure\nKeep output framework-neutral\nCall out related artifacts when useful",
    constraints: "Do not include private data\nDo not invent new top-level taxonomy buckets\nDo not treat protocol mappings as taxonomy replacements",
    inputs: "Artifact id\nUser-provided field values\nPublic-safety notes",
    responseFormat: "Markdown with clear section headings and concise bullets.",
  },
  "interface-schema": {
    interfaceName: "Artifact Draft Request",
    participants: "Learner\nStatic builder UI\nMarkdown renderer",
    inputs: "artifactId: Selected catalog artifact id\nfieldValues: Synthetic user-entered field values\nformatPreference: Optional starter output format",
    outputs: "markdown: Generated starter artifact text\nfilename: Suggested starter filename\nrelatedArtifacts: Catalog artifact ids referenced by the draft",
    errorStates: "Missing required field\nUnknown artifact id\nUnsafe private or regulated example content",
  },
  "memory-policy": {
    memoryScope: "Remember only learner-approved preferences for future public-safe examples.",
    allowedMemory: "Preferred explanation depth\nFavorite generic scenario type\nAccessibility preferences",
    disallowedMemory: "Personal identifiers\nPrivate project names\nSecrets or credentials\nProduction data",
    retention: "Retain until the learner clears preferences or the example workspace is reset.",
    userControls: "View remembered preferences\nEdit remembered preferences\nClear all remembered preferences",
  },
  "state-strategy": {
    stateScope: "Track the current selected artifact and in-progress form values during one browser session.",
    stateFields: "selectedArtifactId: Current catalog artifact id\nformValues: Draft values keyed by artifact id\npreviewText: Current generated Markdown",
    lifecycle: "State is created when the app loads, updated as the learner edits, and cleared when the page is refreshed or reset.",
    expiry: "Session-only unless a future version adds explicit save behavior.",
    recovery: "If state is missing, select the first artifact and start with empty fields.",
  },
  "plan-record": {
    goal: "Create a public-safe starter artifact for a learning scenario.",
    steps: "Select the artifact type\nReview learning notes\nFill guided fields\nCopy or download the generated Markdown",
    dependencies: "Artifact catalog entry\nMarkdown renderer",
    assumptions: "The learner is working with synthetic examples\nThe output is a starter, not a production-ready policy",
    status: "In progress",
  },
  "handoff-contract": {
    handoffName: "Draft Review Handoff",
    sender: "Artifact drafter",
    receiver: "Artifact reviewer",
    contextPackage: "Generated Markdown draft\nSelected catalog artifact\nOpen questions\nKnown public-safety constraints",
    acceptanceCriteria: "Taxonomy bucket is correct\nExamples are synthetic\nRequired fields are filled\nRelated artifacts are named",
  },
  "guardrails-governance-policy": {
    policyScope: "Applies to generated educational artifacts and example values.",
    allowedActions: "Use generic workshop, learning, or planning scenarios\nUse placeholder endpoints and account names\nSummarize safety constraints",
    prohibitedActions: "Include secrets or credentials\nCopy private logs or traces\nUse regulated or employer-specific examples\nAdd a new top-level taxonomy bucket",
    approvalRules: "Ask for review before publishing new example sets\nRequire review for protocol-specific mappings",
    escalation: "Escalate when a requested example appears to contain private, regulated, or proprietary information.",
  },
  "output-schema": {
    schemaName: "Starter Artifact Markdown",
    format: "Markdown",
    requiredFields: "title: Artifact heading\ntaxonomyPlacement: Bucket and lifecycle stage\nfields: Guided field responses\npublicSafetyNotes: Safety reminders",
    constraints: "Use readable headings\nKeep examples synthetic\nPreserve related artifact references",
    exampleOutput: "# Example Artifact\n\n## Taxonomy placement\n\n- Canonical bucket: Identity",
  },
  "eval-rubric": {
    evalGoal: "Assess whether a generated starter artifact is clear, safe, and taxonomy-aligned.",
    criteria: "Correct canonical bucket\nReadable purpose section\nRequired fields represented\nPublic-safety notes included\nRelated artifacts listed",
    scoring: "Score each criterion from 1 to 3, where 1 means missing, 2 means partially useful, and 3 means clear and ready for learner adaptation.",
    testCases: "Generate an agent manifest for a synthetic workshop assistant\nGenerate a memory policy with no personal data\nGenerate a state strategy that does not describe long-term memory",
    observabilityNotes: "Use synthetic review notes only; do not paste real user sessions, traces, or logs.",
  },
  "runtime-config": {
    runtimeName: "Local Static Builder Runtime",
    environment: "Local browser with a static file server",
    dependencies: "Modern browser\nLocal static server",
    limits: "No analytics\nNo remote scripts\nNo persistence beyond the active browser session",
    configuration: "host: localhost\nport: 8000\ncontentRoot: src",
  },
  "iteration-changelog-note": {
    changeSummary: "Added the first static builder shell and generic Markdown generation flow.",
    reason: "Learners need a working app surface before specialized artifact builders are added.",
    evidence: "Catalog entries render by bucket\nPreview updates as fields change\nControls copy, download, reset, and load examples",
    followUps: "Add lightweight validation\nAdd export bundles\nAdd specialized renderers for selected artifacts",
    affectedArtifacts: "agent-manifest\nskill-module\nmemory-policy\nstate-strategy",
  },
};

export default exampleValues;
