export const exampleValues = {
  "agent-manifest": {
    agentName: "Workshop Planning Assistant",
    purpose: "Help a facilitator turn a public workshop idea into clear planning artifacts.",
    scope: "Supports agenda drafting, checklist creation, and follow-up note organization for synthetic workshop scenarios.",
    owners: "Example program facilitator\nLearning experience maintainer",
    relatedSystems: "Public template library\nLocal Markdown workspace\nSynthetic checklist collection",
  },
  "role-profile": {
    role: "Planning collaborator",
    audience: "Builders learning agent artifact design",
    tone: "Clear, practical, and beginner-friendly",
    autonomy: "Medium - drafts for review",
    boundaries: "Drafts artifacts for human review\nDoes not make commitments on behalf of a person\nEscalates unclear safety or privacy questions\nUses only synthetic examples",
  },
  "operating-principles": {
    principles: "Make assumptions visible\nPrefer small reversible steps\nKeep examples public-safe",
    decisionRules: "Ask for review before changing artifact scope\nUse the catalog bucket as the organizing anchor",
    escalationRules: "Escalate when a request includes private data\nPause when taxonomy placement is unclear",
    communicationStyle: "Use concise explanations and show how each artifact connects to nearby artifacts.",
  },
  "skill-module": {
    skillName: "Synthetic Workshop Outline Skill",
    trigger: "Use when a learner needs a reusable workflow for outlining a generic workshop.",
    inputs: "Topic\nAudience level\nTimebox\nDesired artifact outputs",
    workflow: "Clarify the learning goal\nDraft a timed outline\nList required public-safe materials\nIdentify follow-up artifacts",
    outputs: "Workshop outline draft\nMaterials checklist\nRelated artifact list\nOpen questions for review",
  },
  "tool-spec": {
    toolName: "Template Lookup",
    purpose: "Find a matching public-safe starter template from a local collection.",
    parameters: "topic: Public-safe subject string\nartifactType: Catalog artifact id\nformat: markdown | yaml",
    permissions: "Read local public template files\nReturn template metadata only\nAvoid network access in the starter spec",
    failureModes: "No matching template found\nTemplate metadata is incomplete\nRequested artifact type is unknown",
  },
  "resource-manifest": {
    resourceName: "Public Learning Notes",
    resourceType: "Static reference collection",
    allowedUse: "Use as background material for synthetic examples and beginner explanations.",
    freshness: "Review once per release cycle.",
    accessNotes: "Stored as public Markdown files with no private links, credentials, account ids, or private endpoints.",
  },
  "system-task-prompt": {
    promptPurpose: "Guide the model to generate beginner-readable artifact drafts.",
    instructions: "Use the selected catalog artifact as the source of structure\nKeep output framework-neutral\nCall out related artifacts when useful",
    constraints: "Do not include private data\nDo not invent new top-level taxonomy buckets\nDo not treat protocol mappings as taxonomy replacements",
    inputs: "Artifact id\nUser-provided field values\nPublic-safety notes",
    responseFormat: "Markdown with clear section headings and concise bullets.",
  },
  "interface-schema": {
    interfaceName: "Artifact Draft Request",
    participants: "Learner\nStatic builder UI\nMarkdown renderer",
    inputs: "artifactId: Selected catalog artifact id\nfieldValues: Synthetic user-entered field values\nformatPreference: Optional starter output format",
    outputs: "markdown: Generated starter artifact text\nfilename: Suggested starter filename\nrelatedArtifacts: Catalog artifact ids referenced by the draft",
    errorStates: "Missing required field\nUnknown artifact id\nUnsafe private or regulated example content",
  },
  "memory-policy": {
    memoryScope: "Define durable, learner-approved preferences that help a documentation assistant produce future public-safe examples.",
    allowedMemory: "Preferred explanation depth\nPreferred starter artifact format\nFavorite generic scenario type\nAccessibility preferences for generated examples",
    disallowedMemory: "Personal identifiers\nPrivate project names\nSecrets or credentials\nProduction data\nRaw session transcripts or runtime traces",
    retention: "Retain until the learner clears preferences, corrects an entry, or the example workspace is reset.",
    userControls: "View remembered preferences\nCorrect an inaccurate preference\nDelete one remembered preference\nClear all remembered preferences",
  },
  "state-strategy": {
    stateScope: "Track the current selected artifact, visible workflow status, and in-progress form values during one browser session.",
    stateFields: "selectedArtifactId: Current catalog artifact id\nformValues: Draft values keyed by artifact id\npreviewText: Current generated Markdown\napprovalStatus: Whether a user-visible action is pending, approved, declined, or complete\nlastSafeCheckpoint: Synthetic checkpoint label for resume or retry",
    lifecycle: "State is created when the app loads, updated as the learner edits, checkpointed after safe UI actions, and cleared when the page is refreshed or reset.",
    expiry: "Session-only unless a future version adds explicit save behavior.",
    recovery: "If state is missing, select the first artifact and start with empty fields. If a retry is needed, resume from the last documented safe checkpoint and ask again for any missing approval.",
  },
  "plan-record": {
    goal: "Create a public-safe starter artifact for a generic project helper learning scenario.",
    steps: "Select the artifact type\nReview learning notes and related artifacts\nFill guided fields with synthetic values\nCheck the preview for taxonomy alignment\nCopy or download the generated Markdown",
    dependencies: "Artifact catalog entry\nArtifact-specific Markdown renderer\nPublic-safety notes\nReviewer acceptance criteria",
    assumptions: "The learner is working with synthetic examples\nThe output is a starter, not a production-ready policy\nVisible steps and decisions are enough for coordination",
    status: "In progress",
  },
  "handoff-contract": {
    handoffName: "Draft Review Handoff",
    sender: "Documentation assistant",
    receiver: "Public-safe artifact reviewer",
    contextPackage: "Generated Markdown draft\nSelected catalog artifact id\nCurrent visible plan status\nOpen questions\nKnown public-safety constraints\nRelated artifact ids",
    acceptanceCriteria: "Taxonomy bucket is correct\nExamples are synthetic\nRequired fields are filled\nAuthority boundaries are clear\nRelated artifacts are named",
  },
  "guardrails-governance-policy": {
    policyScope: "Applies to a documentation assistant that generates public-safe starter artifacts for generic learning scenarios.",
    allowedActions: "Draft educational Markdown, YAML-like, and JSON examples with synthetic values\nUse generic scenarios such as a research brief helper or task triage workflow\nReference related catalog artifacts by id or suggested filename\nUse placeholders for non-secret settings and adapter names",
    prohibitedActions: "Include secrets, credentials, private URLs, account ids, or customer data\nCopy private logs, real traces, live state snapshots, or memory entries\nUse regulated, proprietary, or employer-specific examples\nTreat MCP, A2A, or other protocols as replacement taxonomy buckets\nAdd a new top-level taxonomy bucket",
    approvalRules: "Ask for review before publishing new example sets\nRequire review before adding a tool with external side effects\nRequire review before changing data handling, approval, or escalation posture\nRequire review for protocol-specific mappings that could be mistaken for taxonomy changes",
    escalation: "Escalate when a requested example appears to contain private, regulated, proprietary, credential-like, or production runtime information.",
  },
  "output-schema": {
    schemaName: "Research Brief Output Contract",
    format: "JSON",
    requiredFields: "title: Short public-safe brief title\nsummary: Concise synthetic summary\nkey_points: List of generic findings or recommendations\nlimitations: Public-safe caveats and missing context\nrelated_artifacts: Catalog artifact ids or filenames referenced by the output",
    constraints: "Use predictable field names\nKeep examples synthetic and generic\nPreserve related artifact references\nReject outputs that require private sources, secrets, or real traces",
    exampleOutput: "{\"title\":\"Generic Topic Brief\",\"summary\":\"Synthetic overview for a learning scenario.\",\"key_points\":[\"Use public-safe source notes\",\"Name related artifacts\"],\"limitations\":\"No private source material was used.\",\"related_artifacts\":[\"output-schema\",\"eval-rubric\"]}",
  },
  "eval-rubric": {
    evalGoal: "Assess whether a generated starter artifact for a generic project helper is clear, public-safe, and aligned to the canonical taxonomy bucket.",
    criteria: "Correct canonical bucket and lifecycle role\nReadable purpose and scope\nRequired catalog fields represented\nPublic-safety notes included\nRelated artifacts named\nBoundary between design-time, runtime, and iteration is preserved",
    scoring: "Score each criterion from 1 to 3, where 1 means missing or unsafe, 2 means partially useful but needs revision, and 3 means clear enough for learner adaptation.",
    testCases: "Generate an agent manifest for a synthetic workshop assistant\nGenerate a memory policy with no personal data or live memory entries\nGenerate a state strategy that does not describe long-term memory\nGenerate a runtime config with placeholder-only secret references\nGenerate an output schema that acts as a contract",
    observabilityNotes: "Review on each renderer change and before public examples are published. Use synthetic review notes only; do not paste real user sessions, traces, transcripts, incidents, or logs.",
  },
  "runtime-config": {
    runtimeName: "Local Documentation Assistant Runtime",
    environment: "Local browser with a static file server and synthetic catalog data",
    dependencies: "Modern browser\nLocal static server\nPublic catalog files\nPlaceholder model profile reference",
    limits: "Request timeout: 30 seconds for any future approved adapter\nRetry limit: 1 safe retry after a documented checkpoint\nNo analytics\nNo remote scripts\nNo persistence beyond the active browser session",
    configuration: "host: localhost\nport: 8000\ncontent_root: src\nmodel_profile: model-profile-placeholder\nsecrets_source: environment-variable-placeholder",
  },
  "iteration-changelog-note": {
    changeSummary: "Added specialized starter renderers for governance, output schema, evaluation rubric, runtime config, and iteration notes.",
    reason: "The remaining catalog entries needed generated output that looked closer to the artifact being built while preserving the generic catalog-driven form experience.",
    evidence: "Renderer lookup includes the five remaining artifact ids\nPreview updates as fields change\nSynthetic examples avoid secrets, private data, logs, traces, and live state\nGeneric fallback remains available for future catalog entries",
    followUps: "Add lightweight automated renderer snapshot checks\nAdd a short catalog renderer coverage table\nReview examples before public release notes\nConsider export bundles after renderer coverage stabilizes",
    affectedArtifacts: "guardrails-governance-policy\noutput-schema\neval-rubric\nruntime-config\niteration-changelog-note",
  },
};

export default exampleValues;
